# Generated by Django 3.0.4 on 2020-03-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200327_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
